cordovaBuild/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cordovaBuild.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return RedirectToAction("Login", "Account");
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult HowDoesItWork()
        {
            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

cordovaBuild/Controllers/PostSpaceController.cs
using cordovaBuild.Common;
using cordovaBuild.Data.Model;
using cordovaBuild.Data.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace cordovaBuild.Controllers
{
    public class PostSpaceController : Controller
    {
        // GET: PostSpace
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        
        [Authorize]
        public async Task<ActionResult> List(string username)
        {
            var postRepository = new PostRepository();
            var spaces = await postRepository.GetSpacesByUser(User.Identity.Name);
            return View(spaces);
        }
        
        public async Task<ActionResult> HeatMap()
        {
            var searchRepository = new SearchRepository();
            var search = await searchRepository.GetAllSearches();


            return View(search);
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Photo()
        {
            var photo = Request.Files["filePhoto"];
            var id = Request["Id"];
            var dir = Server.MapPath("~/Upload/" + User.Identity.Name);
            if (!System.IO.Directory.Exists(dir))
            {
                System.IO.Directory.CreateDirectory(dir);
            }
            var filename = Guid.NewGuid() + Path.GetExtension(photo.FileName);
            var fullPath = Path.Combine(dir, filename);
            photo.SaveAs(fullPath);

            var postRepo = new PostRepository();
            await postRepo.UpdatePhoto(id, fullPath);

            return Json(new { success = true, responseText = "Added." }, JsonRequestBehavior.AllowGet);
        }        

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Post(Space space)
        {
            try
            {
                var postRepo = new PostRepository();

                switch (space.AvailabilityType)
                {
                    case "Specific Date" :
                        if (space.Availability.SpecificDate == DateTime.MinValue)
                        {
                            Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                            return Json(new { success = false, responseText = "Invalid specific date." }, JsonRequestBehavior.AllowGet);
                        }
                        break;
                    case "Date Range":
                        if (space.Availability.DateFrom == DateTime.MinValue || space.Availability.DateTo == DateTime.MinValue)
                        {
                            Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                            return Json(new { success = false, responseText = "Invalid date range." }, JsonRequestBehavior.AllowGet);
                        }
                        break;
                }
                space.Availability.DateFrom = DateTime.SpecifyKind(space.Availability.DateFrom, DateTimeKind.Utc);
                space.Availability.DateTo = DateTime.SpecifyKind(space.Availability.DateTo, DateTimeKind.Utc);
                space.Availability.SpecificDate = DateTime.SpecifyKind(space.Availability.SpecificDate, DateTimeKind.Utc);

                var data = new Data.Model.Space
                {
                    User = User.Identity.Name,
                    Address = space.Address,
                    latitude = space.latitude,
                    longitude = space.longitude,
                    VehicleType = space.VehicleType,
                    NumberOfSlot = space.NumberOfSlot,
                    AvailabilityType = space.AvailabilityType,
                    Availability = space.Availability,
                    Price = space.Price,
                    Instructions = space.Instructions,
                    DatePosted = DateTime.SpecifyKind(DateTime.Now, DateTimeKind.Utc)
                };

                await postRepo.CreateSync(data);

                

                var accountStatement = new AccountStatementRepository();
                var amount = await accountStatement.GetCurrentBalance(User.Identity.Name) + 10;
                var promo = new AccountStatement
                {
                    User = User.Identity.Name,
                    Credit = 10,
                    CurrentBalance = amount,
                    TransactionDate = Helper.SetDateForMongo(DateTime.Now),
                    Description = "Early adopter $10 promo"
                };

                accountStatement.Create(promo);


                return Json(new { success = true, responseText = "Added.", id = data.Id.ToString() }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return Json(new { success = false, responseText = ex.Message }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

cordovaBuild/Controllers/SearchSpaceController.cs
using MongoDB.Bson;
using cordovaBuild.Common;
using cordovaBuild.Data.Model;
using cordovaBuild.Data.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace cordovaBuild.Controllers
{
    public class SearchSpaceController : Controller
    {
        // GET: SearchSpace
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Search(Search search)
        {
            try
            {
                var searchRepo = new SearchRepository();
                var documentId = ObjectId.GenerateNewId();
                searchRepo.Create(new Search 
                {
                    Id = documentId,
                    Address = search.Address,
                    Username = User.Identity.Name,
                    Radius = search.Radius,
                    lat = search.lat,
                    lng = search.lng,
                    SearchDate = Helper.SetDateForMongo(DateTime.UtcNow)
                });

                return Json(new { success = true, responseText = "Added.", id = documentId.ToString(), isAuthenticated = User.Identity.IsAuthenticated }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return Json(new { success = false, responseText = ex.Message }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

cordovaBuild/Controllers/SubscriberController.cs
using cordovaBuild.Data.Model;
using cordovaBuild.Data.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace cordovaBuild.Controllers
{
    public class SubscriberController : Controller
    {
        // GET: Subscriber
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Subscribe(Subscriber subscriber)
        {
            try
            {
                var subscriberRepo = new SubscriberRepository();

                subscriberRepo.Create(new Subscriber
                {
                    Email = subscriber.Email,
                    DateRegistered = DateTime.UtcNow
                });

                return Json(new { success = true, responseText = "Added." }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.InternalServerError;
                return Json(new { success = false, responseText = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

cordovaBuild/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

cordovaBuild/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_LayoutDetailed.cshtml";
}


    <!--// End Team 2-1 --><!-- Start Contact 1 -->
<section class="content-block contact-1">
    <div class="container text-center">

        <div class="col-sm-10 col-sm-offset-1">

            <div class="underlined-title">
                <div class="editContent">
                    <h1>Get in Touch</h1>
                </div>
                <hr>
                <div class="editContent">
                    <h2>We'd love to hear from you. Get in touch today!</h2>
                </div>
            </div>
        <!--
            <div class="editContent">
                <p>Cras mattis consectetur purus sit amet fermentum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam porta sem malesuada magna mollis euismod. Nulla vitae elit libero, a pharetra augue. Aenean eu leo quam. Pellentesque ornare sem lacinia.</p>
            </div>
            -->
            <div class="editContent">
                <ul class="contact-info">
                    <li><span class="fa fa-map-marker"></span>14A Shirley Avenue, Papakura 2110, Auckland, New Zealand</li>
                    <li><span class="fa fa-envelope"></span><a href="mailto:hello@outloud.digital">hello@outloud.digital</a> </li>
                </ul>
            </div>
        


        </div><!-- /.col-sm-10 -->

    </div><!-- /.container -->
</section><!-- /.content-block -->
<!--// END Contact 1 --><!-- Start Footer 1-1 -->

cordovaBuild/Views/Home/HowDoesitWork.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_LayoutDetailed.cshtml";
}

@section meta{
    <meta property="og:image" content="http://www.cordovaBuild.com/Content/images/postingaspace.jpeg" />
}

<section id="content-1-2" class="content-block content-1-2">
    <div class="container">
        <!-- Start Row -->
        <div class="row">
            <div class="col-sm-6">
                <div class="editContent">
                    <h2>How it works?</h2>
                </div>
                <div class="editContent">
                    <p class="lead">We want to save people from the frustrations of not finding an affordable parking space that pushes them to waste their money on parking in expensive carparks. We want to save people from not being able to park their car with convenience while there are actually unused parking spaces.</p>
                </div>
                <div class="editContent">
                    <p>Carpark sharing is not new and a lot of it exist from around the globe. However, we believe that this same system will work here in New Zealand, especially in Auckland where the CBD parking is crazily expensive and street parking is just not enough in most places.</p>
                </div>
                <div class="row">
                    <div class="col-sm-5 col-xs-12">
                        <a href="@Url.Action("Index","PostSpace")" class="btn btn-block btn-primary">Post a Space</a>
                    </div>
                    <div class="col-sm-5 col-xs-12">
                        <a href="@Url.Action("Index","SearchSpace")" class="btn btn-block btn-warning">Find a space</a>
                    </div>
                </div>
            </div>

            <div class="col-sm-5 col-sm-offset-1">
                <img src="/Content/images/postingaspace.jpeg" class="img-responsive" alt="Responsive image">
                <!--
                <div class="embed-responsive embed-responsive-4by3">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/m5qozs0N_WI"
                            width="500" height="400" frameborder="0" allowfullscreen></iframe>
                </div>
                    -->
            </div>
        </div>
        <!--// END Row -->
    </div>
</section>

cordovaBuild/Views/Home/Index.cshtml
@{
    ViewBag.Title = "cordovaBuild";
}

<!--// END Content Block 1-2 --><!-- Start Footer 1-2 -->


@*<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div style="background-color:lightblue; height:100px;">
            <p class="text-center">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">&nbsp;</div>
</div>
<div class="row">
    <div class="col-lg-2 col-lg-offset-4">
        <a class="btn btn-default" href="@Url.Action("Index","PostSpace")" role="button">I'm a car park owner</a>
    </div>
    <div class="col-lg-2">
        <a class="btn btn-default" href="Find.html" role="button">I'm looking for a car park</a>
    </div>
</div>*@


<!--

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>
    -->

<section id="content-1-2" class="content-block content-1-2">
    <div class="container">
        <!-- Start Row -->
        <div class="row">
            <div class="col-sm-6">
                <div class="editContent">
                    <h2>How it works?</h2>
                </div>
                <div class="editContent">
                    <p class="lead">We want to save people from the frustrations of not finding an affordable parking space that pushes them to waste their money on parking in expensive carparks. We want to save people from not being able to park their car with convenience while there are actually unused parking spaces.</p>
                </div>
                <div class="editContent">
                    <p>
                        Carpark sharing is not new and a lot of it exist from around the globe. However, we believe that this same system will work here in New Zealand, especially in Auckland where the CBD parking is crazily expensive and street parking is just not enough in most places.
                    </p>
                </div>
                <div class="row">
                    <div class="col-sm-5 col-xs-12">
                        <a href="@Url.Action("Index","PostSpace")" class="btn btn-block btn-primary">Post a Space</a>
                    </div>
                    <div class="col-sm-5 col-xs-12">
                        <a href="@Url.Action("Index","SearchSpace")" class="btn btn-block btn-warning">Find a space</a>
                    </div>
                </div>
            </div>

            <div class="col-sm-5 col-sm-offset-1">
                <img src="/Content/images/postingaspace.jpeg" class="img-responsive" alt="Responsive image">
                <!--
                <div class="embed-responsive embed-responsive-4by3">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/m5qozs0N_WI"
                            width="500" height="400" frameborder="0" allowfullscreen></iframe>
                </div>
                    -->
            </div>
        </div>
        <!--// END Row -->
    </div>
</section>



<section id="content-2-8" class="content-2-8 content-block-nopad bg-crete">

    <div class="image-container col-sm-6 pull-left">
        <div class="background-image-holder">

        </div>
    </div>

    <div class="container">

        <div class="row">

            <div class="col-md-6 col-md-offset-6 col-sm-7 col-sm-offset-5 col-xs-12 content clearfix">
                <div class="editContent">
                    <h1>Sit tight, our engineers are working on our mobile app!</h1>
                </div>
                <div class="editContent">
                    <p class="lead">We want cordovaBuild to be as handy as possible, accessible anywhere and anytime to help you find the best parking spot.</p>
                </div>
                <div class="row pad15">
                    <div class="col-xs-2">
                        <span class="fa fa-rocket fa-4x"></span>
                    </div>
                    <div class="col-xs-10">
                        <div class="editContent">
                            <h3>Launching very very soon!</h3>
                        </div>
                        <!--
                        <div class="editContent">
                            <p>Retro chillwave YOLO four loko photo booth. Brooklyn kale chips, seitan hella 3 wolf moon slow-carb paleo.</p>
                        </div>
                            -->
                        <div class="alert alert-success" role="alert" id="submittedAlertSubscribe" style="display:none;">Thank You! We are thrilled that you're interested in cordovaBuild. <br /><br />Talk to you shortly, <br /><br />Francis <br />Co-Founder, cordovaBuild</div>
                        <p>We're currently baking our mobile app! Sign up for early access and see what's happening on cordovaBuild mobile app as it happens.</p>
                        <div class="form-group">
                            <input type="text" id="txtSubscriberEmail" class="form-control" placeholder="Your emaill address" />
                        </div>
                        <button type="button" class="btn btn-block btn-danger" id="btnSubscribe">Subscribe</button>
                    </div>
                </div><!-- /.row -->
            </div>

        </div><!-- /.row-->

    </div><!-- /.container -->

</section>

@*<section id="content-1-2" class="content-block content-1-2">
    <div class="container">
        <!-- Start Row -->
        <div class="row">
            <div class="col-sm-6">
                <div class="editContent">
                    <h2>Our blog</h2>
                </div>
                <div class="editContent">
                    <p class="lead">We want to save people from the frustrations of not finding an affordable parking space that pushes them to waste their money on parking in expensive carparks. We want to save people from not being able to park their car with convenience while there are actually unused parking spaces.</p>
                </div>
                <div class="editContent">
                    <p>
                        Carpark sharing is not new and a lot of it exist from around the globe. However, we believe that this same system will work here in New Zealand, especially in Auckland where the CBD parking is crazily expensive and street parking is just not enough in most places.
                    </p>
                </div>
                <div class="row">
                    <div class="col-sm-5 col-xs-12">
                        <a href="@Url.Action("Index","PostSpace")" class="btn btn-block btn-primary">Post a Space</a>
                    </div>
                    <div class="col-sm-5 col-xs-12">
                        <a href="@Url.Action("Index","SearchSpace")" class="btn btn-block btn-warning">Find a space</a>
                    </div>
                </div>
            </div>

            <div class="col-sm-5 col-sm-offset-1">
                <img src="/Content/images/postingaspace.jpeg" class="img-responsive" alt="Responsive image">
                <!--
                <div class="embed-responsive embed-responsive-4by3">
                    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/m5qozs0N_WI"
                            width="500" height="400" frameborder="0" allowfullscreen></iframe>
                </div>
                    -->
            </div>
        </div>
        <!--// END Row -->
    </div>
</section>*@



@section Scripts {
    <script type="text/javascript">
        $("#btnSubscribe").click(function () {
            if (!/^\s*$/.test($("#txtSubscriberEmail").val())) {
                $.ajax({
                    url: '@Url.Action("Subscribe", "Subscriber")',
                    data: { Email: $("#txtSubscriberEmail").val() },
                    dataType: 'json',
                    method: 'POST',
                    success: function (result) {
                        $("#submittedAlertSubscribe").slideDown("slow");
                        $("#txtSubscriberEmail").val();
                    },
                    error: function (xhr, error, errorThrown) {
                    }

                });
            }
        });
    </script>
}